### ISSUE TITLE
Could I check "is ready" if method run for a long time?

### ISSUE THREAD

**Issue by thearabbit** [grovelabs/meteor-call-promise#1]
I want to check `is ready` like `pub/sub` if the method run for along time.
(I use `spinner`)
Please example.

**Comment by cmnjcs** [comment]
Hi @thearabbit, I'm not sure what you're looking for here. Method calls don't do `isReady`, since the end of the method call is what signals that the method is finished running. In other words, if there was a `isReady` function for methods, it would always be `false` until the method call ends.

**Comment by thearabbit** [comment]
I want to use it in template helper like this

``` js
// Server
Meteor.methods({
    add: function () {
        Meteor._sleepForMs(1000);
        return 'Welcome to Promise Call';
    }

// Client
<template name="myTpl">
   {{#if myValue}}
      {{myValue}}
   {{else}}
      {{> spinner}}
   {{/if}}

Template.myTpl.helpers({
   myValue: function(){
      const promise = Meteor.callPromise('add');
        return promise.then(function (res) {
            return res;
        });
   }
})
</template>
```

**Comment by thearabbit** [comment]
But don't get value.

**Comment by cmnjcs** [comment]
@thearabbit we don't use Blaze in our applications, so this is new ground for us. @lourd, would the example work correctly? I'm not entirely certain that the `myValue` helper would return `res` all the way to the template.

**Comment by thearabbit** [comment]
I seem don't understand for difference of `Meteor.call() vs Meteor.callPromise()`.

**Comment by lourd** [comment]
@thearabbit `Meteor.call` and `Meteor.callPromise` are used the same way, the only difference is where the function happens on the return, in a callback or in the resolution of a Promise. 

For Blaze, you have to set a Reactive Data Source for the template to be re-rendered.  Something like a `ReactiveVar` or `Session`. In React, we would use the component's `setState`method.

``` js
// Using Meteor.call
Meteor.call("methodName", (error, result) => {
  // identify the error
  if (error.error === "logged-out") {
    // show a nice error message
    Session.set("errorMessage", "Please log in to post a comment.");
  } else {
    Session.set("foo", result);
  }

 // Using Meteor.callPromise
Meteor.callPromise("methodName")
.then((result) => {
  Session.set("foo", result);
})
.catch((err) => {
  if (error.error === "logged-out") {
    Session.set("errorMessage", "Please log in to post a comment.");
  }
});

```

**Comment by thearabbit** [comment]
Thanks for your explain.
I think that it like `deanius:meteor-promise`.
`

**Comment by lourd** [comment]
You're welcome. Yup, it accomplishes the same thing as that package

**Comment by thearabbit** [comment]
But `deanius:meteor-promise` can return directly and waiting from server.
I think that it is good, if this package do like this.

**Comment by lourd** [comment]
I think what you're trying to assert is by using `deanius:promise` and Blaze, you can wrap one of your template helpers functions in the `PromiseHelper` function and be able to return Promises from that that method. It may look like it's a synchronous return but it's not, there's some [Tracker magic](https://github.com/deanius/meteor-promise/blob/master/promiseHelper.js) implemented behind the scenes that's handling the asynchronous aspect.

**Comment by thearabbit** [comment]
Thank again.
