### ISSUE TITLE
Could I return value of Meteor.callPromise() in template helper?

### ISSUE THREAD

**Issue by thearabbit** [grovelabs/meteor-call-promise#2]
Could I return value of Meteor.callPromise() in template helper?

``` js
data: function(){
   varpromise = Meteor.callPromise('myMethod');
   return promise.then(function (res) {
         return res;
   });
}
```

**Comment by cmnjcs** [comment]
From my comment [here](https://github.com/grovelabs/meteor-call-promise/issues/1#issuecomment-126918868), I'm not clear how Blaze plays with Promises. What happens if you try this example? What does the template render?

**Comment by lourd** [comment]
See https://github.com/grovelabs/meteor-call-promise/issues/1#issuecomment-126938642
